//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBToJSON.SqlEntities.Infusions
{
    using DBToJSON.SqlEntities.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class VariableTimeDilution
    {
        [Key]
        public int InfusionDilutionId { get; set; }
        [ForeignKey("InfusionDrug")]
        public int InfusionDrugId { get; set; }
        public DilutionMethod DilutionMethodId { get; set; }
        public int SiPrefix { get; set; }
        public int? Volume { get; set; }
        public double WeightMin { get; set; }
        public double WeightMax { get; set; }
        public int AgeMinMonths { get; set; }
        public int AgeMaxMonths { get; set; }
        public double RateMin { get; set; }
        public double RateMax { get; set; }
        public bool IsPerMin { get; set; }
        public string ReferencePage { get; set; }
    
        public virtual InfusionDrug InfusionDrug { get; set; }
        public virtual ICollection<VariableTimeConcentration> VariableTimeConcentrations { get; set; }
    }
}
