//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBToJSON.SqlEntities
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class DrugAmpuleConcentration
    {
        [Key]
        public int AmpuleConcentrationId { get; set; }
        [ForeignKey("Drug")]
        public int DrugId { get; set; }
        public double Concentration { get; set; }
        public double? Volume { get; set; }
        public string Description { get; set; }

        public virtual Drug Drug { get; set; }
    }
}
