//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicuDrugsCore.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DrugReferenceSource
    {
        [Key]
        public int DrugReferenceId { get; set; }
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Reference description must be between 5 and 50 characters long")]
        [Required(ErrorMessage = "Reference description must be provided")]
        public string ReferenceDescription { get; set; }
        [StringLength(15, MinimumLength = 3, ErrorMessage = "Reference abbreviation must be between 3 and 15 characters long")]
        [Required(ErrorMessage = "Reference abbreviation must be provided")]
        public string Abbrev { get; set; }
        [StringLength(100, ErrorMessage = "Hyperlink must be <100 characters long")]
        public string Hyperlink { get; set; }
    
        public virtual ICollection<InfusionDrug> InfusionDrugs { get; set; }
    }
}
