//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicuDrugsCore.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class FixedTimeConcentration
    {
        [Key]
        public int InfusionConcentrationId { get; set; }
        [ForeignKey("FixedTimeDilution")]
        public int InfusionDilutionId { get; set; }
        [Range(0.001, 1001, ErrorMessage = "Concentration must be between 0.001 and 1000")]
        public double Concentration { get; set; }
        [Range(FieldConst.minVolume, FieldConst.maxVolume, ErrorMessage = FieldConst.volErr)]
        public Nullable<int> Volume { get; set; }
        [Range(FieldConst.minStop, FieldConst.maxStop, ErrorMessage = FieldConst.stopErr)]
        public int StopMinutes { get; set; }
        [Range(FieldConst.minRate, FieldConst.maxRate, ErrorMessage = FieldConst.rateErr)]
        public double Rate { get; set; }
    
        public virtual FixedTimeDilution FixedTimeDilution { get; set; }
    }
}
